# Generated by Django 3.1b1 on 2020-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('isButt', models.BooleanField(default=False)),
                ('isShaft', models.BooleanField(default=False)),
                ('productName', models.CharField(default=False, max_length=140)),
                ('productNumber', models.CharField(default=False, max_length=140)),
                ('purchasedCustomer', models.CharField(max_length=140)),
                ('purchasedDate', models.DateTimeField(auto_now_add=True)),
                ('warrantyNumber', models.CharField(max_length=140)),
                ('warrantyDate', models.DateTimeField(auto_now_add=True)),
                ('warrantyManager', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
