# Generated by Django 3.1b1 on 2020-07-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='instant_book',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='cue',
            name='lng',
        ),
    ]
