# Generated by Django 3.1b1 on 2020-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cue',
            name='productBrand',
            field=models.CharField(default=False, max_length=140),
        ),
        migrations.AlterField(
            model_name='cue',
            name='productNumber',
            field=models.CharField(blank=True, default=False, max_length=140),
        ),
        migrations.AlterField(
            model_name='cue',
            name='warrantyDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cue',
            name='warrantyNumber',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
