# Generated by Django 3.1b1 on 2020-07-28 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cues', '0002_auto_20200728_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cue',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cue',
            name='lastView',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cue',
            name='warrantyDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
