# Generated by Django 3.1b1 on 2020-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cues', '0003_auto_20200728_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='cue',
            name='purchasedCustomerProtectedName',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
